# Generated by Django 5.2 on 2025-04-22 07:28

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", ckeditor_uploader.fields.RichTextUploadingField()),
                ("name", models.CharField(max_length=156)),
                ("position", models.CharField(max_length=156)),
                ("fb", models.CharField(blank=True, max_length=156, null=True)),
                ("insta", models.CharField(blank=True, max_length=156, null=True)),
                ("linkedin", models.CharField(blank=True, max_length=156, null=True)),
                ("image", models.ImageField(upload_to="SEO")),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tags", models.CharField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("h1", models.CharField(max_length=156)),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=1256, null=True, unique=True
                    ),
                ),
                ("page_name", models.CharField(blank=True, max_length=1256, null=True)),
                ("keyword", models.CharField(max_length=156)),
                ("description", models.CharField(max_length=900)),
                ("title", models.CharField(max_length=156)),
                ("breadcrumb", models.CharField(max_length=156)),
                (
                    "canonical",
                    models.CharField(default="https://.com/", max_length=900),
                ),
                ("og_type", models.CharField(max_length=156)),
                ("og_card", models.CharField(max_length=156)),
                ("og_site", models.CharField(max_length=156)),
                ("image", models.ImageField(upload_to="SEO")),
                ("updated", models.DateField(auto_now=True)),
                ("published", models.DateField()),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "edits",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                ("schema", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.author",
                    ),
                ),
                ("category", models.ManyToManyField(to="blog.category")),
                ("tag", models.ManyToManyField(to="blog.tags")),
            ],
            options={
                "ordering": ["-published"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blog",
                    ),
                ),
            ],
        ),
    ]
