# Generated by Django 5.2 on 2025-04-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blog_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
