# Generated by Django 5.2 on 2025-04-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_contact_feedback_remove_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='role',
            field=models.CharField(default='Author', help_text='Role of the person giving testimonial', max_length=50),
        ),
    ]
