# Generated by Django 5.2 on 2025-04-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testimonial_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, default='static/nopic.webp', help_text='Image for the testimonial.', null=True, upload_to='data'),
        ),
    ]
