# Generated by Django 5.2 on 2025-04-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_testimonial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, default='default/nopic.webp', help_text='Image for the testimonial.', null=True, upload_to='data'),
        ),
    ]
