# Generated by Django 5.2 on 2025-04-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skillbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(help_text='Write the Skill e.g WevDev', max_length=50)),
                ('bar_value', models.FloatField()),
            ],
        ),
    ]
