# Generated by Django 5.2 on 2025-04-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_blog_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="fa_icons",
            field=models.CharField(default="fa fa-code", max_length=100),
        ),
    ]
