# Generated by Django 5.2 on 2025-04-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_services_fa_icons"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="mini_description",
            field=models.CharField(default="LOL", max_length=100),
        ),
        migrations.AlterField(
            model_name="services",
            name="canonical",
            field=models.CharField(
                blank=True,
                default="https://thegrandindianroute.com/",
                max_length=900,
                null=True,
            ),
        ),
    ]
