# Generated by Django 5.2 on 2025-04-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_services_mini_description_alter_services_canonical"),
    ]

    operations = []
