# Generated by Django 5.2 on 2025-04-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_auto_20250421_XXXX"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="icon",
            field=models.ImageField(
                blank=True, default="default/nopic.webp", null=True, upload_to="SEO"
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="image",
            field=models.ImageField(default="default/nopic.webp", upload_to="SEO"),
        ),
    ]
