# Generated by Django 5.2 on 2025-04-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_services_icon_alter_services_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="author",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="category",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="blog",
        ),
        migrations.RemoveField(
            model_name="services",
            name="category",
        ),
        migrations.RemoveField(
            model_name="services",
            name="tag",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Blog",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Tags",
        ),
    ]
