# Generated by Django 5.2 on 2025-04-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_portfoliocategory_portfolioimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioimage",
            name="link",
            field=models.URLField(default="www.vinkdesign.com", max_length=1000),
        ),
    ]
