# Generated by Django 5.2 on 2025-04-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_portfolioimage_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="testimonial_background",
            field=models.ImageField(default="default/parallax-3.jpg", upload_to=""),
        ),
    ]
